# Введение в высшую математику

#### Практическое задание №5

In [1]:
import numpy as np

#### 5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [31]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [32]:
C = A + B
C

array([5, 7, 9])

In [33]:
C = np.dot(A, B)
C

32

In [35]:
C = A * B
C

array([ 4, 10, 18])

In [34]:
C = A * 3
C

array([3, 6, 9])